// <auto-generated />
namespace projekt_gosp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class newdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newdb));
        
        string IMigrationMetadata.Id
        {
            get { return "201604270728495_newdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
