// <auto-generated />
namespace projekt_gosp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _12312213123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12312213123));
        
        string IMigrationMetadata.Id
        {
            get { return "201604301936093_12312213123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
