// <auto-generated />
namespace projekt_gosp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _3232232 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3232232));
        
        string IMigrationMetadata.Id
        {
            get { return "201604301407096_3232232"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
